# Android 构建环境配置
# Shell 路径、工具路径、构建产物路径等

[shell]
# cadroid 项目的路径
path = "../cadroid"

# Gradle Build 时生成的 classes.dex 文件路径，相对于 shell.path
dex_path = ".\\app\\build\\intermediates\\dex\\release\\minifyReleaseWithR8\\classes.dex"

# android.jar 的路径，用于导入类
android_jar_path = "D:\\APPdata\\huangyx\\Local\\Android\\Sdk\\platforms\\android-36\\android.jar"

[shell.tools]

[shell.tools.jarsigner]
path = "D:\\Program Files\\Java\\jdk-11\\bin\\jarsigner.exe"

[shell.tools.apksigner]
# apksigner.jar 路径（在 build-tools 目录下的 lib 文件夹中）
# 使用 jar 文件直接调用，避免 Windows .bat 脚本问题
jar_path = "C:\\Users\\33532\\AppData\\Local\\Android\\Sdk\\build-tools\\36.1.0\\lib\\apksigner.jar"
# Java 可执行文件路径
java_path = "D:\\Program Files\\Java\\jdk-11\\bin\\java.exe"

[shell.tools.zipalign]
path = "C:\\Users\\33532\\AppData\\Local\\Android\\Sdk\\build-tools\\30.0.3\\zipalign.exe"
