# 签名配置
# 签名文件路径、密钥别名等（不含密码）

[sign]
# 签名文件路径，相对于 shell.path
keystore = ".\\app\\signatures\\release.keystore"

# 密钥别名
key_alias = ""

# 正式版安装包签名公钥文件路径，相对于 shell.path
release_pubkey = ".\\app\\signatures\\release.signature"

# 调试用安装包签名公钥文件路径，相对于 shell.path
debug_pubkey = ".\\app\\signatures\\debug.signature"

# 热更新签名用私钥文件路径，相对于 shell.path
hotfix_private_key = ".\\app\\signatures\\privateKey.pem"

# 注意：密码请配置在 sign.local.toml 中，该文件不会被 Git 追踪
